### ISSUE TITLE
Docs containing eclipselink get modified to eclipsexref

### ISSUE THREAD

**Issue by svendiedrichsen** [payara/Payara-Server-Documentation-Antora#8]
The docs found under https://docs.payara.fish/docs/5.201/documentation/payara-server/jpa-cache-coordination.html contain errors. The package names and property names which should contain `eclipselink` do contain `eclipsexref`. Something has scrambled the string `link` to `xref`.

**Comment by fturizo** [comment]
Thanks for reporting this issue, @svendiedrichsen. This was a side-effect of migrating the repository to its new Antora format. We have fixed the problem now.
